/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function ProductCard() {
  return (
    <div className="product-card">
      <header className="product-header">
        <img
          loading="lazy"
          srcSet="..."
          className="product-image"
          alt="Product Image"
        />
      </header>
      <div className="product-price">$1,890.90</div>
      <div className="product-description">Monitor 27” IPS LED FHD</div>
      <a href="#" className="product-button">
        Buy
      </a>
      <style jsx>{`
        .product-card {
          justify-content: center;
          align-items: center;
          border-radius: 14px;
          background-color: var(--Dop, #f5f5f7);
          display: flex;
          max-width: 290px;
          flex-direction: column;
          padding: 20px;
        }

        .product-header {
          aspect-ratio: 1.26;
          object-fit: contain;
          object-position: center;
          width: 146px;
          overflow: hidden;
          align-self: center;
          max-width: 100%;
        }

        .product-price {
          color: var(--Text, #222231);
          text-align: center;
          align-self: center;
          margin-top: 12px;
          white-space: nowrap;
          font: 400 22px/91% Arial, sans-serif;
        }

        .product-description {
          align-self: stretch;
          color: var(--Dop-gray, #6a6a71);
          text-align: center;
          letter-spacing: 0.16px;
          margin-top: 6px;
          white-space: nowrap;
          font: 400 16px/140% Arial, -apple-system, Roboto, Helvetica,
            sans-serif;
        }

        .product-button {
          color: var(--White, #fff);
          text-align: center;
          letter-spacing: 1.08px;
          white-space: nowrap;
          justify-content: center;
          border-radius: 6px;
          background-color: var(--Main, #ea44a8);
          align-self: center;
          margin-top: 12px;
          padding: 8px 30px;
          font: 400 18px/133% Arial, -apple-system, Roboto, Helvetica,
            sans-serif;
        }
      `}</style>
    </div>
  );
}
