/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { MdOutlineEmail } from "react-icons/md";
import { InfoCardItem } from "./InfoCardItem";

import "./infoCard.scss";

export const InfoCard = ({
  extraClass = "",
  vector = <MdOutlineEmail size={32} className="mx-auto my-3" />,
  items = [
    {
      property: "Email",
      value: "youremail@gmail.com",
    },
    {
      property: "Skype",
      value: "@yourusername",
    },
    {
      property: "Telegram",
      value: "@yourusername",
    },
  ],
}) => {
  return (
    <div
      className={`d-flex flex-column col-lg-3 col-md-4 col-sm-6 col-xs-10 border ${extraClass}`}
    >
      {vector}
      <div className="col-10 mx-auto d-flex flex-column py-3">
        {items.map(({ property, value, index }) => (
          <InfoCardItem key={index} property={property} value={value} />
        ))}
      </div>
    </div>
  );
};
